#Jon Crawford

#makefile for Home Cooked Bacon

HOME = /mnt/c/Users/jonat/'Google Drive'/School/PastSemesters/COP4530
CC = g++ -std=c++11 -Wall -Wextra -I. -I$(HOME)/cpp -I$(HOME)/tcpp

kb.x: kb.cpp moviematch.h
	$(CC) -o kb.x kb.cpp
